<h3>Add/Edit New Prescription</h3>
<table>
    <tr>
        <td class="lefttd">Starting Date</td>
        <td><select name="start_date_m">
                <option value="01" label="January">January</option>
                <option value="02" label="February">February</option>
                <option value="03" label="March">March</option>
                <option value="04" label="April">April</option>
                <option value="05" label="May">May</option>
                <option value="06" label="June">June</option>
                <option value="07" label="July">July</option>
                <option value="08" label="August">August</option>
                <option value="09" label="September">September</option>
                <option value="10" label="October">October</option>
                <option selected="selected" value="11" label="November">November</option>
                <option value="12" label="December">December</option>
            </select>
            <select name="start_date_d">
                <option value="1" label="01">01</option>
                <option value="2" label="02">02</option>
                <option value="3" label="03">03</option>
                <option value="4" label="04">04</option>
                <option selected="selected" value="5" label="05">05</option>
                <option value="6" label="06">06</option>
                <option value="7" label="07">07</option>
                <option value="8" label="08">08</option>
                <option value="9" label="09">09</option>
                <option value="10" label="10">10</option>
                <option value="11" label="11">11</option>
                <option value="12" label="12">12</option>
                <option value="13" label="13">13</option>
                <option value="14" label="14">14</option>
                <option value="15" label="15">15</option>
                <option value="16" label="16">16</option>
                <option value="17" label="17">17</option>
                <option value="18" label="18">18</option>
                <option value="19" label="19">19</option>
                <option value="20" label="20">20</option>
                <option value="21" label="21">21</option>
                <option value="22" label="22">22</option>
                <option value="23" label="23">23</option>
                <option value="24" label="24">24</option>
                <option value="25" label="25">25</option>
                <option value="26" label="26">26</option>
                <option value="27" label="27">27</option>
                <option value="28" label="28">28</option>
                <option value="29" label="29">29</option>
                <option value="30" label="30">30</option>
                <option value="31" label="31">31</option>
            </select>
            <select name="start_date_y">
                <option value="2017" label="2017">2017</option>
                <option value="2016" label="2016">2016</option>
                <option value="2015" label="2015">2015</option>
                <option value="2014" label="2014">2014</option>
                <option value="2013" label="2013">2013</option>
                <option selected="selected" value="2012" label="2012">2012</option>
                <option value="2011" label="2011">2011</option>
                <option value="2010" label="2010">2010</option>
                <option value="2009" label="2009">2009</option>
                <option value="2008" label="2008">2008</option>
                <option value="2007" label="2007">2007</option>
                <option value="2006" label="2006">2006</option>
                <option value="2005" label="2005">2005</option>
                <option value="2004" label="2004">2004</option>
                <option value="2003" label="2003">2003</option>
                <option value="2002" label="2002">2002</option>
            </select>
        </td>
    </tr>
    <tr>
        <td class="lefttd">Provider</td>
        <td><input type="text" value="Dr Poxos"></td>
    </tr>
    <tr>
        <td class="lefttd">Drug</td>
        <td><input type="text" value=""> (Click to search)</td>
    </tr>
    <tr>
        <td class="lefttd">Medicine Units</td>
        <td><input type="text" value="" name="size">
            <select id="unit" name="unit">
                <option value="0" label=" "> </option>
                <option value="1" label="mg">mg</option>
                <option value="2" label="mg/1cc">mg/1cc</option>
                <option value="3" label="mg/2cc">mg/2cc</option>
                <option value="4" label="mg/3cc">mg/3cc</option>
                <option value="5" label="mg/4cc">mg/4cc</option>
                <option value="6" label="mg/5cc">mg/5cc</option>
                <option value="7" label="mcg">mcg</option>
                <option value="8" label="grams">grams</option>
            </select></td>
    </tr>
    <tr>
        <td class="lefttd">Take In</td>
        <td><input type="text" name="dosage" value="Per Oris"
                   title="Type" size="12"> 
            <input type="text" name="duration" value="2"
                   title="Duration (in days)" size="6">
            <input type="text" name="periodicity" value="3" 
                   title="Periodicity (per day)" size="6">
            <input type="text" name="interval" value="" 
                   title="Inteval (hour, optional)" size="6"></td>
    </tr>
    <tr>
        <td class="lefttd">Notes</td>
        <td><textarea rows="2" cols="30" name="note"></textarea></td>
    </tr>
    <tr>
        <td class="lefttd">Substitution allowed</td>
        <td><input type="radio" checked="checked" value="0" 
                   name="medication">No 
            <input type="radio" value="1" 
                   name="medication"> Yes
        </td>
    </tr>
                <tr>
        <td class="lefttd"></td>
        <td><input type="button" value="Save" name="save"></td>
    </tr>
</table>
<?php
// put your code here
?>
